sequel:
  users:
    endpoint: sqlite://users.db
    test_connection: true

logger:
  file: app.log
  rotate_days: 30
  rotate_size: 102400000
  date_format: '%Y-%m-%d %H:%M:%S +Z'
  log_format: "%time,%sev,%pid,%tid,%mod,%json\n------------------\n"
  black_list: [pass, password, clabe, telefono, mobile, email, mail]

aws:
  default_keys:
    key: AKIA818AD3DLKD
    secret: 91$jsad.123^`aks012jeLa+`
    region: us-east-1
  s3:
    user_record:
      bucket: ant-qa-users
    log_record:
      bucket: logprovider-qa-log
      key: AKIA99812AKDLA1
      secret: OO=A18+$.alsk1jsla1s
      region: eu-west-1
      test_connection:
        list: {}
        put: ant_testing.txt
        get: ant_testing.txt
  sqs:
    etl_pipeline:
      queue: ant-etl_pipeline
      test_connection: true
    mailing:
      queue: ant-mailing

rest_clients:
  github:
    basic_auth:
      user: Ant
      pass: SecretPassword
    protocol: https
    host: api.github.com
    validator: none
    format: json
  wallet:
    protocol: http
    host: ant-wallet.com
    validate: jsend
    format: json

nanoservice:
  models:
    users:
      fields:
        username:
          type: string
          # alphanumeric:
          #   extra_chars: '._-'
          size: 32
          not_null:
          keys:
            primary: true
        borndate:
          type: string
          not_null:
          # keys:
          #   index: true
        email:
          type: string
          size: 64
          not_null:
          regex: '\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z'
          # index: true
        mobile:
          type: string
          not_null:
          size: 16
          # index: true
      configs: {}
